name: engz_2
description: "Artisan Services App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # State Management
  flutter_bloc: ^9.1.1
  provider: ^6.1.5

  # API Requests
  dio: ^5.9.0

  # Local Storage
  shared_preferences: ^2.5.3

  # Location
  geolocator: ^14.0.2

  # OpenStreetMap
  flutter_map: ^8.2.1
  latlong2: ^0.9.1

  # Images
  cached_network_image: ^3.4.1
  image_picker: ^1.2.0

  # SVG Icons
  flutter_svg: ^2.2.0

  # Animations
  lottie: ^3.3.2

  # UI
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.2.1

  # Utilities
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/